apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: myprivaterepo.azurecr.io/client
          ports:
            - name: http
              containerPort: 80
          env:
            - name: PORT
              value: "3001"
            - name: API
              value: "server-svc"
