apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: myprivaterepo.azurecr.io/server
          ports:
            - name: http
              containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DB_URI
              value: "mongodb+srv://admin:admin@cluster0.gkmmv.mongodb.net/new_DB?retryWrites=true&w=majority"
